# Generated by Django 5.0.3 on 2024-04-03 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session',
            new_name='GameSession',
        ),
    ]
