# Generated by Django 5.0.3 on 2024-04-03 17:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_app', '0003_rename_gamesession_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='session',
            name='date',
        ),
        migrations.RemoveField(
            model_name='session',
            name='is_recurring',
        ),
        migrations.RemoveField(
            model_name='session',
            name='time',
        ),
        migrations.RemoveField(
            model_name='session',
            name='weekday',
        ),
        migrations.AddField(
            model_name='session',
            name='dateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='session',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='proj_app.player'),
        ),
    ]
