# Generated by Django 5.0.3 on 2024-04-03 17:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_app', '0004_player_remove_session_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='dateTime',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name='session',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
