# Generated by Django 5.0.3 on 2024-04-03 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_app', '0005_alter_session_datetime_alter_session_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proj_app.player'),
        ),
    ]
