# Generated by Django 5.0.3 on 2024-04-04 18:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_app', '0007_alter_session_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='dateTime',
        ),
        migrations.AddField(
            model_name='session',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='session',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
