# Generated by Django 5.0.3 on 2024-04-07 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj_app', '0009_session_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='owner',
        ),
    ]
