# Generated by Django 5.0.3 on 2024-04-18 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj_app', '0013_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='max_players',
        ),
    ]
