# Generated by Django 5.0.3 on 2024-04-18 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_app', '0014_remove_game_max_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='proj_app.game'),
        ),
    ]
