# Generated by Django 5.0.3 on 2024-04-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_app', '0015_alter_session_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='game',
        ),
        migrations.AddField(
            model_name='session',
            name='game_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='thumbnail',
            field=models.URLField(null=True),
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
