# Generated by Django 5.0.3 on 2024-04-19 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj_app', '0016_remove_session_game_session_game_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='is_public',
        ),
    ]
