# Generated by Django 5.0.3 on 2024-04-22 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj_app', '0017_remove_session_is_public'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
